### ISSUE TITLE
Feature: treat Album name as a keyword when exporting

### ISSUE THREAD

**Issue by AHThomas** [RhetTbull/photosmeta#9]
My goal is to export all of my photos to JPG and preserve all of the metadata that I've added to them via the Photos app.  Album names can be considered metadata, essentially just another way of tagging or adding a keyword to photos.  I'd like to have the Album names stored as keywords in the JPG files so that the info is saved and can be used in other apps.

**Comment by RhetTbull** [comment]
Thanks -- I'll add this feature as soon as I get a chance.

**Comment by RhetTbull** [comment]
@AHThomas I've added this to photosmeta, new option: `--albums-as-keywords` which stores the album name as a keyword. Give it a try and let me know if this does what you need.

**Comment by RhetTbull** [comment]
Completed with addition of `--albums-as-keywords`
